package burp_jyconsole.event.controller;

public enum BurpJyConsoleControllerEvent {
    CURRENT_SCRIPT_UPDATED,
    CURRENT_SCRIPT_ENABLE_TOGGLE,
    CURRENT_SCRIPT_CONTENT_UPDATED,
    NAME_UPDATED,
    SCRIPT_TYPE_UPDATED,
    CANCEL,
    DELETE,
    SAVE,
    NEW,
    SCRIPT_SELECTION_UPDATED,
    OUTPUT_UPDATED,
    OUTPUT_TYPE_UPDATED,
    OUTPUT_TYPE_STDOUT_SELECTED,
    OUTPUT_TYPE_STDERR_SELECTED,
    IMPORT,
    EXPORT,
    CLEAR_OUTPUT,
    TABLE_VALUE_UPDATED,
    SCRIPT_LANGUAGE_UPDATED,
    TOGGLE_SCRIPT_EXECUTION
}
