package burp_hotpatch.event.model;

public enum BurpHotpatchModelEvent {
    CONFIG_LOADED,
    SCRIPT_OUTPUT_UPDATED,
    SCRIPTS_SET,
    STDERR_SET,
    STDOUT_SET,
    CURRENT_SCRIPT_SET,
    SCRIPT_DELETED,
    OUTPUT_FORMAT_SET,
    SCRIPT_SAVED,
    SCRIPT_TEMPLATE_MODIFIED,
    CURRENT_SCRIPT_SAVE_ERROR,
    UPDATE_AVAILABLE_MESSAGE_UPDATED,
    EXECUTION_THREAD_ADDED,
    EXECUTION_THREAD_REMOVED,
    RUNNING_TASK_ADDED,
    RUNNING_TASK_REMOVED,
    CURRENT_TASK_SET,
    EDITOR_STATE_SET
}
